# Generated by Django 4.1 on 2023-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_image',
            field=models.CharField(default='https://aironova.in/uploads/product/noimage.png', max_length=500),
        ),
    ]
